from typing import Tuple, List, Optional, Text, BinaryIO, Union, Sequence, \
    ByteString, Callable, Any, TypeVar

def pyyoga_version() -> int: ...
def pyyoga_version_string() -> str: ...

class YGNodeRef:
    def __init__(): ...

def ygnode_new() -> YGNodeRef: ...
def ygnode_free(node: YGNodeRef): ...