from typing import Tuple, List, Optional, Text, BinaryIO, Union, Sequence, \
    ByteString, Callable, Any, TypeVar

def poga_version() -> int: ...
def poga_version_string() -> str: ...

class YGNodeRef: ...

def YGNodeNew() -> YGNodeRef: ...
def YGNodeFree(node: YGNodeRef): ...