name: poga

channels:
  - conda-forge
  - default

dependencies:
  - python=3.9
  - pip>=22.2.2
  - black>=22.6.0
  - sphinx>=5.1.1
  - pybind11>=2.8.1
  - pytest>=7.1.2
  - pip:
    - myst_parser>=0.18.1
    - piccolo-theme>=0.12.0

